module.exports = [
    {
        city: "Prague",
        latitude: 50.00556939344721,
        longitude: 14.418105467732193,
        neighborhood: "Modřany",
        pNum: 12,
        openingTime: "9:00-17:00",
        openingDays: "Every Thursday",
        openingDaysArr: ["Thursday"],
        description: "Since the last year, the farmers' market in Modrany is rather a small one. Still, you should be able to purchase fresh vegetables, Slovakian salami and sausages, and bakery products.",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Prior Mall",
        id: 1,
        shortcut: "modrany"
    },
    {
        city: "Prague",
        latitude: 50.128523894398306,
        longitude: 14.489335939993547,
        neighborhood: "Prosek",
        pNum: 9,
        openingTime: "8:00-15:00",
        openingDays: "Every Tuesday and Thursday",
        openingDaysArr: ["Tuesday", "Thursday"],
        description: "Here you can purchase fresh fruits and vegetables, meats, salami and sausages, dairy and bakery products, pastry and spices.",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Poliklinika Prosek",
        id: 2,
        shortcut: "prosek"
    },
    {
        city: "Prague",
        latitude: 50.07487958241222,
        longitude: 14.432289937346042,
        neighborhood: "Vinohrady",
        pNum: 2,
        openingTime: "9:00-18:00",
        openingDays: "Monday to Friday, from mid-April to mid-November",
        openingDaysArr: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        description: "Here you can purchase meats, fruits, vegetables, and herbs, dairy products and goat cheeses, honey, Moravian wines. Besides, you can purchase ceramics, flowers and plants on Tylak.",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Tylovo Square (Tylak)",
        id: 3,
        shortcut: "vinohrady_tylak"

    },
    {
        city: "Prague",
        latitude: 50.100982907596496,
        longitude: 14.394691546915922,
        neighborhood: "Dejvice",
        pNum: 6,
        openingTime: "8:00-14:00",
        openingDays: "Every Saturday",
        openingDaysArr: ["Saturday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Kulaťák",
        id: 4,
        shortcut: "dejvice"
    },

    

    {
        city: "Prague",
        latitude: 50.047662059636224,
        longitude: 14.354785584563064,
        neighborhood: "Smíchov",
        pNum: 5,
        openingTime: "10:00-18:00",
        openingDays: "Every Wednesday",
        openingDaysArr: ["Wednesday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market by Butovice Mall",
        id: 5,
        shortcut: "smichov_butovice"
    },

    {
        city: "Prague",
        latitude: 50.071649613165036,
        longitude: 14.394691546915922,
        neighborhood: "Smíchov",
        pNum: 5,
        openingTime: "8:00-19:00",
        openingDays: "Every Friday",
        openingDaysArr: ["Friday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Anděl",
        id: 6,
        shortcut: "smichov_andel"
    },

    {
        city: "Prague",
        latitude: 50.051241247612886,
        longitude: 14.43913528456317,
        neighborhood: "Pankrác",
        pNum: 4,
        openingTime: "08:00-18:00",
        openingDays: "Every Wednesday",
        openingDaysArr: ["Wednesday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market by Pankrác Mall",
        id: 7,
        shortcut: "pankrac"
    },

    {
        city: "Prague",
        latitude: 50.030177053609144,
        longitude: 14.524102795640795,
        neighborhood: "Háje",
        pNum: 11,
        openingTime: "8:00-18:00",
        openingDays: "Every Monday and Wednesday",
        openingDaysArr: ["Monday","Wednesday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Mother Theresa Community Center",
        id: 8,
        shortcut: "haje"
    },

    {
        city: "Prague",
        latitude: 50.13874680843554,
        longitude: 14.51353237107139,
        neighborhood: "Letňany",
        pNum: 9,
        openingTime: "7:00-12:00",
        openingDays: "Every Saturday",
        openingDaysArr: ["Saturday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Letňany",
        id: 9,
        shortcut: "letnany"
    },

    {
        city: "Prague",
        latitude: 50.07850595232764,
        longitude: 14.450343173517291,
        neighborhood: "Vinohrady",
        pNum: 2,
        openingTime: "8:00-18:00(-14:00 on Saturday)",
        openingDays: "Every Wednesday to Saturday, 25th January to 21th December",
        openingDaysArr: ["Wednesday", "Thursday", "Friday", "Saturday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Jiřák",
        id: 10,
        shortcut: "vinohrady_jirak"
    },

    {
        city: "Prague",
        latitude: 50.070677386593594, 
        longitude: 14.41409399807968,
        neighborhood: "Nové Město",
        pNum: 2,
        openingTime: "8:00-14:00",
        openingDays: "Every Saturday, February to Christmas",
        openingDaysArr: ["Saturday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Náplavka",
        id: "11",
        shortcut: "naplavka"
    },

    {
        city: "Prague",
        latitude: 50.04984067460811, 
        longitude: 14.34441832691454,
        neighborhood: "Stodůlky",
        pNum: 13,
        openingTime: "8:00-18:00",
        openingDays: "Every Monday, April to Christmas",
        openingDaysArr: ["Monday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Sluneční Square",
        id: "12",
        shortcut: "stodulky"
        //Desítka stánků nabízí obyvatelům nejen Prahy 13 ovoce, zeleninu, koření, květiny a další farmářské produkty.
    },
    {
        city: "Prague",
        latitude: 50.10047894967146,
        longitude: 14.444699784587394,
        neighborhood: "Holešovice",
        pNum: 6,
        openingTime: "8:00-17:00(-14:00 on Saturday)",
        openingDays: "Monday to Saturday",
        openingDaysArr: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        description: "lorem",
        webpage: "https://www.prazska-trznice.cz/zeleninovy-trh",
        contact: "contact",
        title: "Farmers' Market at Prague Market (Hall 22)",
        id: "13",
        shortcut: "holesovice"
        //Denně tu najdete čerstvé ovoce a zeleninu, čerstvé bylinky, ryby, maso, vejce a mléčné výrobky, pečivo,
        //ale i bezobalové bio potraviny, asijské nebo ruské speciality a sezónní sazenice. 
    },
    {
        city: "Prague",
        latitude: 50.106590581931115,
        longitude: 14.560112811574095,
        neighborhood: "Černý Most",
        pNum: 14,
        openingTime: "8:00-19:00",
        openingDays: "Every Wednesday",
        openingDaysArr: ["Wednesday"],
        description: "lorem",
        webpage: "http://www.platany.cz/rajska-zahrada/",
        contact: "contact",
        title: "Farmers' Market at Rajská zahrada",
        id: "14",
        shortcut: "rajskazahrada"
    },
    {
        city: "Prague",
        latitude: 50.108302595930446, 
        longitude: 14.577701526894524,
        neighborhood: "Černý Most",
        pNum: 14,
        openingTime: "8:00-14:00",
        openingDays: "Every Saturday",
        openingDaysArr: ["Saturday"],
        description: "lorem",
        webpage: "http://www.platany.cz/cerny-most/",
        contact: "contact",
        title: "Farmers' Market at Černý Most",
        id: "15",
        shortcut: "cernymost"
    },
    {
        city: "Prague",
        latitude: 50.045156616720135, 
        longitude: 14.478041169243198, 
        neighborhood: "Spořilov",
        pNum: 4,
        openingTime: "08:00-14:00",
        openingDays: "Every Saturday",
        openingDaysArr: ["Saturday"],
        description: "lorem",
        webpage: "http://www.platany.cz/sporilov/",
        contact: "contact",
        title: "Farmers' Market at Spořilov",
        id: "16",
        shortcut: "sporilov"
    },
    {
        city: "Prague",
        latitude: 50.091704976499294, 
        longitude: 14.448531855751437,
        neighborhood: "Karlín",
        pNum: 6,
        openingTime: "8:00-18:00",
        openingDays: "Every Friday",
        openingDaysArr: ["Friday"],
        description: "lorem",
        webpage: "https://www.facebook.com/karlinmarket/",
        contact: "contact",
        title: "Farmers' Market at Karlín Market",
        id: "17",
        shortcut: "karlin"
    },
    {
        city: "Prague",
        latitude: 50.09711361052011,  
        longitude: 14.423294540409353,
        neighborhood: "Holešovice",
        pNum: 7,
        openingTime: "9:00-17:00",
        openingDays: "Every Friday, May to July",
        openingDaysArr: ["Friday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at National Museum of Agriculture",
        id: "18",
        shortcut: "holesovice_nma"
    },
    {
        city: "Prague",
        latitude: 50.0347230053852,
        longitude: 14.37731620977185,
        neighborhood: "Barrandov",
        pNum: 5,
        openingTime: "8:00-18:00",
        openingDays: "Every Thursday",
        openingDaysArr: ["Thursday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Tilleho Square",
        id: "19",
        shortcut: "barrandov"
    },
    {
        city: "Prague",
        latitude: 50.133568414512176,
        longitude: 14.377256269246102,
        neighborhood: "Suchdol",
        pNum: 5,
        openingTime: "14:00-20:00",
        openingDays: "Every Thursday",
        openingDaysArr: ["Thursday"],
        description: "lorem",
        webpage: "webpage",
        contact: "contact",
        title: "Farmers' Market at Brandejsovo Square",
        id: "20",
        shortcut: "suchdol"
    },

]



